import type { DashboardWidgetSchema } from '@/types/admin/dashboard';

export const adminDashboardBoardSchema: DashboardWidgetSchema[] = [
  {
    appearance: 'glow',
    description: 'Keep the dashboard lean on purpose: lead with users, roles, and permissions now, then add richer widgets only when the board has real signals worth showing.',
    eyebrow: 'Global board',
    id: 'anchor',
    size: 'hero',
    source: 'overview',
    title: 'Open the board, then move straight into access work.',
    widget: 'anchor',
    variant: 'neutral',
  },
  {
    appearance: 'outline',
    ctaLabel: 'Open users',
    description: 'Review the people who can currently reach the workspace and adjust them without wading through filler.',
    emptyDescription: 'No user accounts exist yet. Add the first account before the board tries to tell a bigger story.',
    emptyTitle: 'No user accounts live yet.',
    eyebrow: 'Action surface',
    id: 'users-action',
    size: 'third',
    source: 'users',
    title: 'Users',
    widget: 'action',
    variant: 'success',
  },
  {
    appearance: 'tinted',
    ctaLabel: 'Open roles',
    description: 'Keep reusable policies clear so demos and operational builds can speak the same access language.',
    emptyDescription: 'No roles exist yet. Define the reusable access groups before the board grows more complex than the ACL itself.',
    emptyTitle: 'No roles live yet.',
    eyebrow: 'Action surface',
    id: 'roles-action',
    size: 'third',
    source: 'roles',
    title: 'Roles',
    widget: 'action',
    variant: 'warning',
  },
  {
    appearance: 'glow',
    ctaLabel: 'Open permissions',
    description: 'Use precise permission checks when workflows need guardrails tighter than a broad role can provide.',
    emptyDescription: 'No permission checks exist yet. Add the workflow gates first and leave the decorative graphing for later.',
    emptyTitle: 'No permissions live yet.',
    eyebrow: 'Action surface',
    id: 'permissions-action',
    size: 'third',
    source: 'permissions',
    title: 'Permissions',
    widget: 'action',
    variant: 'error',
  },
  {
    appearance: 'outline',
    description: 'Accounts currently wired into the workspace.',
    eyebrow: 'Snapshot',
    id: 'users-stat',
    size: 'third',
    source: 'users',
    title: 'Users',
    widget: 'stat',
    variant: 'primary',
  },
  {
    appearance: 'tinted',
    description: 'Reusable access groups ready to be assigned.',
    eyebrow: 'Snapshot',
    id: 'roles-stat',
    size: 'third',
    source: 'roles',
    title: 'Roles',
    widget: 'stat',
    variant: 'secondary',
  },
  {
    appearance: 'glow',
    description: 'Workflow gates already available to wire in.',
    eyebrow: 'Snapshot',
    id: 'permissions-stat',
    size: 'third',
    source: 'permissions',
    title: 'Permissions',
    widget: 'stat',
    variant: 'accent',
  },
  {
    appearance: 'glow',
    description: 'This board is the launch surface for real work, not a dumping ground for random dashboard furniture.',
    eyebrow: 'Keep it honest',
    id: 'support',
    items: [
      'Add a widget only when it either starts work faster or explains a real system state cleanly.',
      'Keep domain color assignments consistent so the board can scale without looking like a sticker wall.',
      'Prefer empty-state guidance over fake activity, and keep charts off the board until they have honest data.',
    ],
    size: 'full',
    title: 'Grow the board deliberately, not decoratively.',
    widget: 'support',
    variant: 'info',
  },
];
